services:
  web_service:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
  nginx:
    build:
      context: .
      dockerfile: ./compose/nginx/Dockerfile
    ports:
      - '443:443'
    depends_on:
      - web_service
    logging:
      options:
        max-size: '10m'
        max-file: '3'
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media


volumes:
  media_volume:
  static_volume:
  postgres_data:
  redis_data:
